name: Docker Image CI

on:
  push:
    branches: [ release/1.13.7, release/1.13.6 ]
  pull_request:
    branches: "**"
  create:
    tags: "**"
jobs:
  acas-roo-server:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chemistry_package: [ indigo, bbchem ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            bbolt/acas-roo-server-oss
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule-${{ matrix.chemistry_package }}
            type=ref,event=branch-${{ matrix.chemistry_package }}
            type=ref,event=pr-${{ matrix.chemistry_package }}
            type=semver,pattern={{version}}-${{ matrix.chemistry_package }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.chemistry_package }}
            type=semver,pattern={{major}}-${{ matrix.chemistry_package }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile-${{ matrix.chemistry_package }}
